### ISSUE TITLE
提交反馈的页面有误

### ISSUE THREAD

**Issue by wenketel** [FirefoxBar/Translation#1]
[原帖帖子](http://tieba.baidu.com/p/5211490393)

> 在提交反馈的页面（https://qsurvey.mozilla.com/s3/FirefoxInput/ ）中，有“Firefox让我不满”和“Firefox让我高兴”两个按钮。
> 点击“Firefox让我不满”，出现的页面中显示“……请描述您喜欢哪个地方……”；点击“Firefox让我高兴”，出现的页面中显示“……请在下面描述您遇到的问题，越具体越好……”。可以看出，按钮和点击后出现的页面的对应关系是错误的，应该反过来。
> 
![中文](http://imgsrc.baidu.com/forum/pic/item/386abffd5266d0160b0b63849d2bd40734fa35b8.jpg)
中文，点进去和外面的描述是相反的。
![英文](http://imgsrc.baidu.com/forum/pic/item/094b583d269759ee71b68167b8fb43166f22dfed.jpg)
英文，点进去和外面的描述是对应的

@yfdyh000  这算是翻译的问题还是网站的问题？

**Comment by wenketel** [comment]
https://pontoon.mozilla.org/zh-CN/mozillaorg/tabzilla/tabzilla.lang/?string=52679
话说我更新了翻译你会收到提醒吗？

**Comment by yfdyh000** [comment]
https://github.com/mozilla-l10n/input-l10n/blob/f8e471947d8cb5f4fc7a00930bc8a2bc390ef99b/zh_CN/LC_MESSAGES/django.po#L693 显示翻译没颠倒。翻译项目已不存在于Pontoon项目。
https://bugzilla.mozilla.org/show_bug.cgi?id=1015424 及 https://wiki.mozilla.org/Firefox/Input 显示Input项目已取消，改为外部供应商。

也许工作人员复制翻译时弄颠倒了？浏览器设置ja优先，日语好像也是颠倒的。
提交了 https://bugzilla.mozilla.org/show_bug.cgi?id=1379393

**Comment by yfdyh000** [comment]
@wenketel 不会，没有提醒。已更新。注意空格。

**Comment by lychichem** [comment]
文科你要记得打完链接加个空格啊不然后面的文字也会被识别为链接的……

**Comment by wenketel** [comment]
@lychichem   还真没注意

**Comment by yfdyh000** [comment]
修好了。
